name: WalletPool Calibrator
on:
  schedule:
    - cron: '0 1 * * *' # daily 01:00 UTC
  workflow_dispatch:

jobs:
  calibrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        run: npm ci
        working-directory: github
      - name: Run calibrator
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
          WALLET_LIST: ${{ secrets.WALLET_LIST }}
        run: node scripts/wallet_calibrator.js
        working-directory: github
