name: WalletPool Calibrator
on:
schedule:
- cron: '0 1 * * *'
workflow_dispatch:


jobs:
calibrate:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Setup Node
uses: actions/setup-node@v4
with:
node-version: 18
- name: Run calibrator placeholder
run: echo "implement calibrator script in github/scripts/wallet_calibrator.js"