name: Heavy SmartScore Runner
on:
  schedule:
    - cron: '30 2 * * *' # روزانه 02:30 UTC
  workflow_dispatch:

jobs:
  compute:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install
        run: npm ci
        working-directory: github

      - name: Run scorer batch (process candidates from KV and recompute scores)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          node scripts/scorer_batch.js
        working-directory: github

      - name: Save logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scorer-logs
          path: github/logs || github/**/logs
